sonar.projectKey=desofs2026-wed-ffs-2_desofs2026-wed-ffs-2
sonar.organization=desofs2026-wed-ffs-2

sonar.sources=backend/src/main/java,backend/src/main/resources
sonar.tests=backend/src/test/java
sonar.java.binaries=backend/target/classes
sonar.junit.reportPaths=backend/target/surefire-reports,backend/target/failsafe-reports
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
sonar.exclusions=backend/src/main/java/com/desofs/project/**/dtos/*.java
sonar.coverage.exclusions=backend/src/main/java/com/desofs/project/**/dtos/*.java


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=desofs2026_wed_ffs_2
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
